services:
  rp0-bankapp-ui:
    build: .
    image: rp0-bankapp-ui:1.0.0
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

# docker-compose up --build (if image needs to be built first)
# docker-compose down (stops and removes the containers, networks, and volumes)
